spring:
  application:
    name: s_pay_mall
    version: 1.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/s_pay_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456


server:
  port: 8092


weixin:
  config:
    originalid: gh_19f26f0891cf
    token: b806
    appid: wx0722f6e980b51e47
    secret: 383454c09c935626e41c60bdfb70d73a
    template_id: RbEZ2jo47dQmF4A7_Ku7RsDy1x_5by6bk1Ox6rPCl4Y

# 支付宝 - 沙箱测试
alipay:
  enabled: true
  app_id: 9021000135657223
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiRcr0a7aRSN7wZoxflP6rtFiJTc71vrhFC9Lvj+ypxbBJ/SrkvCVXrIXk3yo0AEyOCLW8IuIjA89YU6P16G5phYXZUsi5nx/muThh9UYQaCsWF5dfJ691HRi74Mo7DILP6YCF1oZfw2QkjSIDN/JUTpO8s5XmOfexv4x/Cj5/MlD57Yi+ZtXC/tDqZ81lFBiZApdsHFUHus/hepGAjrmODSdFpYRj3FxnaVLjeEqTuqXWW/7Ee2QdkSQElfmS35i1rj+I9+wHBD/H7JsYNQAq0/t2kTVD7piV9Ts32dbvVxBSdef/hmaHabNauZWJt//vkF00Y9Q/vLfFeBbZvMypAgMBAAECggEAQxpzZAHK3Gdy8ZymfbwiWCTa2+SWKd81WjAaiUBOEKKUVPRhMXdwRcItGEkErb5V6gJGDMesFei0bIUh70WvqukxQX5PTRs1WPbNDw0bbRt2fctBqHLDxr1Chibd2e9BhPK9WBsvNBibp9XI8+XFywE3bLgiy7K68AES+1HkKDqeiTu7cNjonAc1h2FVAVHM2r8ARDtUDo1bssxc4Fd3rkE6iIp1to25qHdMeCJ/CHvzrsX/I0IWq/DYzvO3qE+ymN7PZoDpNT7NlER5B6P6suMTEJLNePoWmCyL1fB2b2tVrQqq5NLNbw56saOYU0IxvpPq4dyH0BlZWMfAvJZ0BQKBgQDwhPX9ikeOXN2FXPJfifASNrOV3Kvatf7TrjYuLr2qSg0DxNSOOKfIPZ2BuAwdmug68k/l+yJRHw79Tzc3HNlYaGynbmZcphrAYzoZJWSvDhsyFXlZaF3mFiyaFElWJP8WGReFtFAb6pJPvldb+PNMWFmALenqa/8uLQVlPIaOJwKBgQCst49Mls2CPVV4aowMi4yhQgN76f5zXjfcC0pcatE9KFo/WkQ/2Tyuennhvla7OL6A5Lr7zac7dhA5PmQXRxe1YaMdFWrhfhATzROjt6cGR/V/WmgVoeQmCFElIoDxFll6fWCwfmm9/6iHdTedF2sTkzsx32cvTC1dvsn7EtVgrwKBgQCTyF6NJoXJB25lHzMdWNfVmR7HGgvOGr00u3o27ilDlLRieHJR4KXW92Tr63YmSqQec/x7xs7TIU5Ifn/isSsqkx8P0Vm726PcShvMj5lJplU3dNJXCTWIxl8pXQWilKDXpxs44A3I2VyE+uMac+CqLC7x/0QW8bydVrRV+9aBSQKBgH4Ab+9c+NIx8p+lg0RHrjGamjYVMAd0TeYe6oHff4RRYv1i2fWGgwl62l4A4P8212vq8ipvDriHWjCYvqZou/gcIcY+8LlOoWYAr3o5qgUgDA57owFdGLdSS/h+Ynj/aAm/XAGGR5hP4d/oeMkG45vlRkMNCxbrSRFh9bJQPBCLAoGANGHsVSUZ1JdcJJuAsIQxHnZ1rgcibNlrkXEgVCGBqMhs9DMfku9mWObhcg1Ucj24D0nGWmP7H0USIeHF4oCYIF1qZWfTsKiXq+0H86xrcFPWjKhsE93oPXoVHypL+EFw99dBjP1sTrgjWE+8BRsaCbbXWf/7ulSOG+SLMT/N63Y=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtMKnaarsj9tWbk/uS86eEjOEACDkiRynJBRXEhiCdJh2EAWE7uwJthLXZsL/2VZgec+571S0co/UjGrx4mle96neQl3gmDxQw2PpaIc+enuyVXY2zzp1+z0ooYKlC+0C9dfHYKV1qm/JXz1m2dx6McT5HLjV4/PoRxntrXpT+wJ+gPcby8wTlNIsOKgfOBMUegBMZ1jH1sfkq1u5GgUP9BXBEaX8CMGOZtgij8spsmcuR8Ci3Xf6iiGbiH+0NCkWvLgXdT/zzT6GAnH9OIpeQsrY3C4OrnDptEM3jnJNGERW3puM4EDhiSx9UXcNYU/mlfgP1tm9K/1bHcDcDAIvHQIDAQAB
  notify_url: http://openicu4209.natapp1.cc/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do



# 日志打印
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
mybatis:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml